setup: &setup
  adapter: postgresql
  username: postgres
  password: 
  host: localhost
  encoding: UTF8

development:
  <<: *setup
  database: connector_dev

test:
  <<: *setup
  database: connector_test

production:
  <<: *setup
  database: connector_prod
